version: "3"
services:
    namenode:
        build: ./api
        hostname: namenode
        ports:
            - 9870:9870
            - 5000:5000
            - 8020:8020
        env_file:
            - ./config
        environment:
            ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    datanode1:
        image: apache/hadoop:3
        command: ["hdfs", "datanode"]
        env_file:
            - ./config
    datanode2:
        image: apache/hadoop:3
        command: ["hdfs", "datanode"]
        env_file:
            - ./config
    resourcemanager:
        image: apache/hadoop:3
        hostname: resourcemanager
        command: ["yarn", "resourcemanager"]
        ports:
            - 8088:8088
        env_file:
            - ./config
    nodemanager:
        image: apache/hadoop:3
        command: ["yarn", "nodemanager"]
        env_file:
            - ./config
    mongo:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

    kafka:
        image: "bitnami/kafka:latest"
        ports:
            - "9092:9092"
            - "9094:9094"
        environment:
            # KRaft settings
            - KAFKA_CFG_NODE_ID=1
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
            # Listener settings
            - KAFKA_BROKER_ID=1
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
            # Other settings
            - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
            - BITNAMI_DEBUG=yes
            - KAFKA_CFG_NUM_PARTITIONS=2
    kafka-ui:
        image: provectuslabs/kafka-ui
        container_name: kafka-ui
        ports:
            - "18080:8080"
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        depends_on:
            - kafka
